export type Option = {
  value: string
  label: string
}

export const COUNTRY_CODE_OPTIONS: Option[] = [
  { value: "+1", label: "United States / Canada (+1)" },
  { value: "+7", label: "Kazakhstan / Russia (+7)" },
  { value: "+20", label: "Egypt (+20)" },
  { value: "+27", label: "South Africa (+27)" },
  { value: "+31", label: "Netherlands (+31)" },
  { value: "+32", label: "Belgium (+32)" },
  { value: "+33", label: "France (+33)" },
  { value: "+34", label: "Spain (+34)" },
  { value: "+39", label: "Italy (+39)" },
  { value: "+41", label: "Switzerland (+41)" },
  { value: "+44", label: "United Kingdom (+44)" },
  { value: "+45", label: "Denmark (+45)" },
  { value: "+46", label: "Sweden (+46)" },
  { value: "+47", label: "Norway (+47)" },
  { value: "+49", label: "Germany (+49)" },
  { value: "+52", label: "Mexico (+52)" },
  { value: "+54", label: "Argentina (+54)" },
  { value: "+55", label: "Brazil (+55)" },
  { value: "+60", label: "Malaysia (+60)" },
  { value: "+61", label: "Australia (+61)" },
  { value: "+62", label: "Indonesia (+62)" },
  { value: "+63", label: "Philippines (+63)" },
  { value: "+64", label: "New Zealand (+64)" },
  { value: "+65", label: "Singapore (+65)" },
  { value: "+66", label: "Thailand (+66)" },
  { value: "+81", label: "Japan (+81)" },
  { value: "+82", label: "South Korea (+82)" },
  { value: "+84", label: "Vietnam (+84)" },
  { value: "+86", label: "China (+86)" },
  { value: "+91", label: "India (+91)" },
  { value: "+92", label: "Pakistan (+92)" },
  { value: "+93", label: "Afghanistan (+93)" },
  { value: "+94", label: "Sri Lanka (+94)" },
  { value: "+95", label: "Myanmar (+95)" },
  { value: "+234", label: "Nigeria (+234)" },
  { value: "+254", label: "Kenya (+254)" },
  { value: "+353", label: "Ireland (+353)" },
  { value: "+352", label: "Luxembourg (+352)" },
  { value: "+852", label: "Hong Kong (+852)" },
  { value: "+853", label: "Macau (+853)" },
  { value: "+966", label: "Saudi Arabia (+966)" },
  { value: "+971", label: "United Arab Emirates (+971)" },
  { value: "+974", label: "Qatar (+974)" },
]

export const CURRENCY_OPTIONS: Option[] = [
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "USD", label: "USD - US Dollar" },
  { value: "ZAR", label: "ZAR - South African Rand" },
]

export const NATIONALITY_OPTIONS: Option[] = [
  { value: "American", label: "American" },
  { value: "Argentine", label: "Argentine" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Belgian", label: "Belgian" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "British", label: "British" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Croatian", label: "Croatian" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Dutch", label: "Dutch" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Emirati", label: "Emirati" },
  { value: "Filipino", label: "Filipino" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Hong Konger", label: "Hong Konger" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Korean", label: "Korean" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Luxembourgish", label: "Luxembourgish" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Philippine", label: "Philippine" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Qatari", label: "Qatari" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Saudi", label: "Saudi" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "South African", label: "South African" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Thai", label: "Thai" },
  { value: "Turkish", label: "Turkish" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Vietnamese", label: "Vietnamese" },
]

export const SALARY_RANGE_OPTIONS: Record<string, Option[]> = {
  AED: [
    { value: "0-100k AED", label: "Under 100k AED" },
    { value: "100k-200k AED", label: "100k - 200k AED" },
    { value: "200k-300k AED", label: "200k - 300k AED" },
    { value: "300k-500k AED", label: "300k - 500k AED" },
    { value: "500k+ AED", label: "500k+ AED" },
  ],
  AUD: [
    { value: "0-70k AUD", label: "Under 70k AUD" },
    { value: "70k-100k AUD", label: "70k - 100k AUD" },
    { value: "100k-140k AUD", label: "100k - 140k AUD" },
    { value: "140k-180k AUD", label: "140k - 180k AUD" },
    { value: "180k+ AUD", label: "180k+ AUD" },
  ],
  BDT: [
    { value: "0-600k BDT", label: "Under 600k BDT" },
    { value: "600k-1200k BDT", label: "600k - 1.2M BDT" },
    { value: "1200k-2000k BDT", label: "1.2M - 2M BDT" },
    { value: "2000k-3500k BDT", label: "2M - 3.5M BDT" },
    { value: "3500k+ BDT", label: "3.5M+ BDT" },
  ],
  CAD: [
    { value: "0-60k CAD", label: "Under 60k CAD" },
    { value: "60k-90k CAD", label: "60k - 90k CAD" },
    { value: "90k-130k CAD", label: "90k - 130k CAD" },
    { value: "130k-170k CAD", label: "130k - 170k CAD" },
    { value: "170k+ CAD", label: "170k+ CAD" },
  ],
  CHF: [
    { value: "0-80k CHF", label: "Under 80k CHF" },
    { value: "80k-120k CHF", label: "80k - 120k CHF" },
    { value: "120k-160k CHF", label: "120k - 160k CHF" },
    { value: "160k-220k CHF", label: "160k - 220k CHF" },
    { value: "220k+ CHF", label: "220k+ CHF" },
  ],
  CNY: [
    { value: "0-150k CNY", label: "Under 150k CNY" },
    { value: "150k-300k CNY", label: "150k - 300k CNY" },
    { value: "300k-500k CNY", label: "300k - 500k CNY" },
    { value: "500k-800k CNY", label: "500k - 800k CNY" },
    { value: "800k+ CNY", label: "800k+ CNY" },
  ],
  EUR: [
    { value: "0-40k EUR", label: "Under 40k EUR" },
    { value: "40k-70k EUR", label: "40k - 70k EUR" },
    { value: "70k-100k EUR", label: "70k - 100k EUR" },
    { value: "100k-140k EUR", label: "100k - 140k EUR" },
    { value: "140k+ EUR", label: "140k+ EUR" },
  ],
  GBP: [
    { value: "0-30k GBP", label: "Under 30k GBP" },
    { value: "30k-60k GBP", label: "30k - 60k GBP" },
    { value: "60k-90k GBP", label: "60k - 90k GBP" },
    { value: "90k-120k GBP", label: "90k - 120k GBP" },
    { value: "120k+ GBP", label: "120k+ GBP" },
  ],
  HKD: [
    { value: "0-240k HKD", label: "Under 240k HKD" },
    { value: "240k-480k HKD", label: "240k - 480k HKD" },
    { value: "480k-720k HKD", label: "480k - 720k HKD" },
    { value: "720k-1000k HKD", label: "720k - 1M HKD" },
    { value: "1000k+ HKD", label: "1M+ HKD" },
  ],
  IDR: [
    { value: "0-120m IDR", label: "Under 120M IDR" },
    { value: "120m-240m IDR", label: "120M - 240M IDR" },
    { value: "240m-400m IDR", label: "240M - 400M IDR" },
    { value: "400m-700m IDR", label: "400M - 700M IDR" },
    { value: "700m+ IDR", label: "700M+ IDR" },
  ],
  INR: [
    { value: "0-5 LPA", label: "Under 5 LPA" },
    { value: "5-10 LPA", label: "5 - 10 LPA" },
    { value: "10-20 LPA", label: "10 - 20 LPA" },
    { value: "20-40 LPA", label: "20 - 40 LPA" },
    { value: "40+ LPA", label: "40+ LPA" },
  ],
  JPY: [
    { value: "0-4m JPY", label: "Under 4M JPY" },
    { value: "4m-7m JPY", label: "4M - 7M JPY" },
    { value: "7m-10m JPY", label: "7M - 10M JPY" },
    { value: "10m-15m JPY", label: "10M - 15M JPY" },
    { value: "15m+ JPY", label: "15M+ JPY" },
  ],
  KES: [
    { value: "0-1m KES", label: "Under 1M KES" },
    { value: "1m-2.5m KES", label: "1M - 2.5M KES" },
    { value: "2.5m-4m KES", label: "2.5M - 4M KES" },
    { value: "4m-6m KES", label: "4M - 6M KES" },
    { value: "6m+ KES", label: "6M+ KES" },
  ],
  MYR: [
    { value: "0-60k MYR", label: "Under 60k MYR" },
    { value: "60k-120k MYR", label: "60k - 120k MYR" },
    { value: "120k-180k MYR", label: "120k - 180k MYR" },
    { value: "180k-280k MYR", label: "180k - 280k MYR" },
    { value: "280k+ MYR", label: "280k+ MYR" },
  ],
  NGN: [
    { value: "0-6m NGN", label: "Under 6M NGN" },
    { value: "6m-12m NGN", label: "6M - 12M NGN" },
    { value: "12m-20m NGN", label: "12M - 20M NGN" },
    { value: "20m-35m NGN", label: "20M - 35M NGN" },
    { value: "35m+ NGN", label: "35M+ NGN" },
  ],
  NOK: [
    { value: "0-500k NOK", label: "Under 500k NOK" },
    { value: "500k-800k NOK", label: "500k - 800k NOK" },
    { value: "800k-1100k NOK", label: "800k - 1.1M NOK" },
    { value: "1100k-1500k NOK", label: "1.1M - 1.5M NOK" },
    { value: "1500k+ NOK", label: "1.5M+ NOK" },
  ],
  NZD: [
    { value: "0-70k NZD", label: "Under 70k NZD" },
    { value: "70k-100k NZD", label: "70k - 100k NZD" },
    { value: "100k-140k NZD", label: "100k - 140k NZD" },
    { value: "140k-180k NZD", label: "140k - 180k NZD" },
    { value: "180k+ NZD", label: "180k+ NZD" },
  ],
  PHP: [
    { value: "0-500k PHP", label: "Under 500k PHP" },
    { value: "500k-1000k PHP", label: "500k - 1M PHP" },
    { value: "1000k-1800k PHP", label: "1M - 1.8M PHP" },
    { value: "1800k-3000k PHP", label: "1.8M - 3M PHP" },
    { value: "3000k+ PHP", label: "3M+ PHP" },
  ],
  QAR: [
    { value: "0-120k QAR", label: "Under 120k QAR" },
    { value: "120k-240k QAR", label: "120k - 240k QAR" },
    { value: "240k-360k QAR", label: "240k - 360k QAR" },
    { value: "360k-500k QAR", label: "360k - 500k QAR" },
    { value: "500k+ QAR", label: "500k+ QAR" },
  ],
  SAR: [
    { value: "0-120k SAR", label: "Under 120k SAR" },
    { value: "120k-240k SAR", label: "120k - 240k SAR" },
    { value: "240k-360k SAR", label: "240k - 360k SAR" },
    { value: "360k-500k SAR", label: "360k - 500k SAR" },
    { value: "500k+ SAR", label: "500k+ SAR" },
  ],
  SEK: [
    { value: "0-450k SEK", label: "Under 450k SEK" },
    { value: "450k-700k SEK", label: "450k - 700k SEK" },
    { value: "700k-1000k SEK", label: "700k - 1M SEK" },
    { value: "1000k-1400k SEK", label: "1M - 1.4M SEK" },
    { value: "1400k+ SEK", label: "1.4M+ SEK" },
  ],
  SGD: [
    { value: "0-60k SGD", label: "Under 60k SGD" },
    { value: "60k-100k SGD", label: "60k - 100k SGD" },
    { value: "100k-150k SGD", label: "100k - 150k SGD" },
    { value: "150k-220k SGD", label: "150k - 220k SGD" },
    { value: "220k+ SGD", label: "220k+ SGD" },
  ],
  THB: [
    { value: "0-600k THB", label: "Under 600k THB" },
    { value: "600k-1200k THB", label: "600k - 1.2M THB" },
    { value: "1200k-2000k THB", label: "1.2M - 2M THB" },
    { value: "2000k-3500k THB", label: "2M - 3.5M THB" },
    { value: "3500k+ THB", label: "3.5M+ THB" },
  ],
  TRY: [
    { value: "0-600k TRY", label: "Under 600k TRY" },
    { value: "600k-1200k TRY", label: "600k - 1.2M TRY" },
    { value: "1200k-2000k TRY", label: "1.2M - 2M TRY" },
    { value: "2000k-3200k TRY", label: "2M - 3.2M TRY" },
    { value: "3200k+ TRY", label: "3.2M+ TRY" },
  ],
  USD: [
    { value: "0-50k USD", label: "Under 50k USD" },
    { value: "50k-100k USD", label: "50k - 100k USD" },
    { value: "100k-150k USD", label: "100k - 150k USD" },
    { value: "150k-200k USD", label: "150k - 200k USD" },
    { value: "200k+ USD", label: "200k+ USD" },
  ],
  ZAR: [
    { value: "0-300k ZAR", label: "Under 300k ZAR" },
    { value: "300k-600k ZAR", label: "300k - 600k ZAR" },
    { value: "600k-900k ZAR", label: "600k - 900k ZAR" },
    { value: "900k-1300k ZAR", label: "900k - 1.3M ZAR" },
    { value: "1300k+ ZAR", label: "1.3M+ ZAR" },
  ],
  DEFAULT: [
    { value: "Entry", label: "Entry" },
    { value: "Mid", label: "Mid" },
    { value: "Senior", label: "Senior" },
    { value: "Lead", label: "Lead" },
  ],
}

export function getSalaryRangesForCurrency(currency: string) {
  return SALARY_RANGE_OPTIONS[currency] || SALARY_RANGE_OPTIONS.DEFAULT
}
